<?php

use Phinx\Migration\AbstractMigration;

class Alt2Oc13532 extends AbstractMigration
{

    public function up()
    {
        $sql = <<<SQL
        UPDATE db_layoutcampos SET db52_default = 'PAGAMENTO DE SALARIO' WHERE db52_nome = 'mensagemdoc' AND db52_layoutlinha = (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE LOTE');

        INSERT INTO db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT db50_codigo FROM db_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB'), 'HEADER DE ARQUIVO', 1, 240, 0, 0, '', '', false);

        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'db90_codban', 'CÓDIGO DO BANCO NA COMPENSACAO', 2, 1, '', 3, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'registroheaderarq', 'REGISTRO HEADER DE ARQUIVO', 2, 8, '0', 1, true, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 9, '', 9, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'tipoinscricao', 'TIPO DE INSCRIÇÃO DA EMPRESA', 2, 18, '2', 1, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'cgc', 'CGC DA PREFEITURA', 7, 19, '', 14, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'conveniobanco', 'CODIGO DO CONVENIO DO BANCO', 2, 33, '', 20, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'agenciaheader', 'AGENCIA MANTENEDORA DA CONTA', 2, 53, '', 5, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'dvagenciaheader', 'DIGITO VERIFICADOR DA AGENCIA', 1, 58, '', 1, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'contaheader', 'NUMERO DA CONTA CORRENTE', 2, 59, '', 12, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'dvcontaheader', 'DIGITO VERIFICADOR DA CONTA', 1, 71, '', 1, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'dvagenciacontaheader', 'DIGITO VERIFICADOR DA AG/CONTA', 1, 72, '', 1, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'nomeinst', 'NOME DA PREFEITURA', 1, 73, '', 30, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'db90_descr', 'NOME DO BANCO', 1, 103, '', 30, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'usofebraban2', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 133, '', 10, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'codigoremessa', 'INDICA QUE ARQUIVO E REMESSA', 2, 143, '1', 1, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'datageracao', 'DATA DE GERACAO DO ARQUIVO', 4, 144, '', 0, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'horageracao', 'HORA DE GERACAO DO ARQUIVO', 5, 152, '', 0, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'sequencialarq', 'NUMERO SEQUENCIAL DO ARQUIVO', 2, 158, '', 6, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'datalancamento', 'DATA DE LANCAMENTO', 4, 172, '', 0, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'loteservico', 'LOTE DE SERVICO', 2, 4, '0000', 4, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'layoutarq', 'VERSAO DO LAYOUT DO ARQUIVO', 1, 164, '087', 3, false, true, 'd', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'densidadearquivo', 'DENSIDADE DE GRAVACAO DO ARQUIVO', 2, 167, '01600', 5, false, true, 'e', '', 0);
        INSERT INTO db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT db51_codigo FROM db_layouttxt JOIN db_layoutlinha ON db50_codigo = db51_layouttxt WHERE db50_descr = 'CNAB240 BANCO SICOOB' AND db51_descr = 'HEADER DE ARQUIVO'), 'brancos', 'BRANCOS', 1, 180, '', 61, false, true, 'd', '', 0);
SQL;

        $this->execute($sql);

    }

    public function down()
    {

    }
}
