<?php

use ECidade\Suporte\Phinx\PostgresMigration;

class Oc14285 extends PostgresMigration
{
    public function up()
    {
        if ($this->checkMenu()) {

            $sql = "
          INSERT INTO db_itensmenu VALUES ((SELECT max(id_item)+1 FROM db_itensmenu),'Arquivo Bradesco CNAB 240', 'Arquivo Bradesco CNAB 240','pes2_bradesco240cnab001.php',1,1,'','t');
          INSERT INTO db_menu VALUES (7908,(SELECT id_item FROM db_itensmenu WHERE funcao = 'pes2_bradesco240cnab001.php'),(SELECT MAX(menusequencia)+1 FROM db_menu WHERE id_item = 7908),952);

          ";
          $this->execute($sql);
        }

        if ($this->checkLayout()) {
            $this->insertLayout();
        }
    }

    public function down()
    {
        $sql = "
        DELETE FROM db_menu where id_item_filho = (SELECT id_item FROM db_itensmenu WHERE funcao = 'pes2_bradesco240cnab001.php');
        DELETE FROM db_itensmenu WHERE funcao = 'pes2_bradesco240cnab001.php';
        ";

        $this->execute($sql);
    }

    private function checkLayout()
    {
        $result = $this->fetchRow("SELECT * FROM configuracoes.db_layouttxt WHERE db50_descr = 'CNAB240 BANCO BRADESCO'");
        if (empty($result)) {
            return true;
        }
        return false;
    }

    private function checkMenu()
    {
        $result = $this->fetchRow("SELECT id_item FROM db_itensmenu WHERE funcao = 'pes2_bradesco240cnab001.php'");
        if (empty($result)) {
            return true;
        }
        return false;
    }

    private function insertLayout()
    {
        $sql = <<<SQL
        BEGIN;
        INSERT INTO configuracoes.db_layouttxt (db50_codigo, db50_descr, db50_quantlinhas, db50_obs, db50_layouttxtgrupo) VALUES ((SELECT max(db50_codigo)+1 FROM db_layouttxt), 'CNAB240 BANCO BRADESCO', 0, '', 1);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'REGISTRO - SEGMENTO A', 3, 240, 0, 0, NULL, NULL, false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CODIGO DO BANCO NA COMPENSACAO', 2, 1, '', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'sequencialnolote', 'SEQUENCIAL DO REGISTRO NO LOTE', 2, 9, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipomovimento', 'TIPO DE MOVIMENTO', 2, 15, '', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registrodetalhelote', 'REGISTRO DETALHE DO LOTE', 1, 8, '3', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'segmentoregistro', 'CODIGO DE SEGMENTO DO REGISTRO DETALHE', 1, 14, 'A', 1, true, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'instrucaomovimento', 'INSTRUCAO PARA MOVIMENTO', 2, 16, '', 2, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'compensacao', 'CODIGO DA CAMARA CENTRALIZADORA', 2, 18, '000', 3, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagenciafavorecido', 'DIGITO VERIFICADOR DA AGENCIA', 1, 29, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvcontafavorecido', 'DIGITO DA CONTA', 1, 42, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagenciacontafav', 'DIGITO DA AG/CONTA FAVORECIDO', 1, 43, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_nome', 'NOME DO FAVORECIDO', 1, 44, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'numerocontrolemov', 'NUMERO DE CONTROLE DO MOVIMENTO', 1, 74, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipomoeda', 'TIPO DA MOEDA', 1, 102, 'BRL', 3, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'numerobanco', 'NUMERO ATRIBUIDO PELO BANCO', 1, 135, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'informacao2', 'OUTRAS INFORMACOES', 1, 178, '', 40, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 218, '', 12, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'ocorrenciasreg', 'CODIGOS DAS OCORRENCIAS', 1, 231, '', 10, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'bancofavorecido', 'CODIGO DO BANCO DO FAVORECIDO', 2, 21, '', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'agenciafavorecido', 'AGENCIA MANTENEDORA DA CONTA FAVORECIDO', 2, 24, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'contafavorecido', 'NUMERO DA CONTA CORRENTE FAVORECIDO', 2, 30, '', 12, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'datarealprocessament', 'DATA DA EFETIVACAO DO PROCESSAMENTO', 2, 155, '', 8, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'avisofavorecido', 'AVISAR FAVORECIDO (0 INDICA NAO)', 2, 230, '0', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dataprocessamento', 'DATA PARA PROCESSAMENTO DO MOVIMENTO', 4, 94, '', 0, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'quantidademoeda', 'QUANTIDADE DA MOEDA', 3, 105, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valordebito', 'VALOR DO LANÇAMENTO', 3, 120, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valrealprocessament', 'VALOR REAL LANCADO', 3, 163, '', 15, false, true, 'e', '', 0);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'REGISTRO - SEGMENTO B', 3, 240, 0, 0, NULL, NULL, false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'segmentoregistro', 'CODIGO DE SEGMENTO DO REGISTRO DETALHE', 1, 14, 'B', 1, true, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'codigofavorecido', 'CODIGO DO FAVORECIDO', 1, 211, '', 15, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 15, '', 3, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_ender', 'ENDERECO (RUA, AV., PÇA, ETC)', 1, 33, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_compl', 'ENDERECO (CASA, APTO, SALA, ETC)', 1, 68, '', 15, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_bairro', 'ENDERECO (BAIRRO)', 1, 83, '', 15, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_munic', 'ENDERECO (NOME DA CIDADE)', 1, 98, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_uf', 'ENDERECO (SIGLA ESTADO)', 1, 126, '', 2, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipoinscricaofav', 'TIPO DE INSCRIÇÃO DO FAVORECIDO', 2, 18, '', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_numero', 'ENDERECO (NUMERO DO LOCAL)', 2, 63, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'datavencimento', 'DATA DO VENCIMENTO (NOMINAL)', 4, 128, '', 0, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_cep', 'ENDERECO (CEP)', 6, 118, '', 0, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'z01_cgccpf', 'CGC / CPF DO FAVORECIDO', 7, 19, '', 14, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valorvencimento', 'VALOR DO DOCUMENTO (NOMINAL)', 3, 136, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valorabatimento', 'VALOR DO ABATIMENTO', 3, 151, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valordesconto', 'VALOR DO DESCONTO', 3, 166, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valormora', 'VALOR DA MORA', 3, 181, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valormulta', 'VALOR DA MULTA', 3, 196, '', 15, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registrodetalhelote', 'REGISTRO DETALHE DO LOTE', 1, 8, '3', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CODIGO DO BANCO NA COMPENSACAO', 2, 1, '', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'sequencialnolote', 'SEQUENCIAL DO REGISTRO NO LOTE', 2, 9, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban2', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 226, '', 15, false, true, 'd', '', 0);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'TRAILLER DE LOTE', 4, 240, 0, 0, NULL, NULL, false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registrotraillerlote', 'REGISTRO TRAILLER DE LOTE', 1, 8, '5', 1, true, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 9, '', 9, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valortotallote', 'SOMATORIO DOS VALORES DO LOTE', 3, 24, '', 18, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'valortotalmoedas', 'SOMATORIO DE QUANTIDADE DE MOEDAS', 3, 42, '', 18, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CODIGO DO BANCO NA COMPENSACAO', 2, 1, '', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'quantidadetotallote', 'QUANTIDADE TOTAL DE REGISTROS DO LOTE', 2, 18, '', 6, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban2', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 60, '000000', 171, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'ocorrenciastralote', 'CODIGOS DAS OCORRENCIAS', 1, 231, '', 10, false, true, 'd', '', 0);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'HEADER DE LOTE', 2, 240, 0, 0, '', '', false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CODIGO DO BANCO NA COMPENSACAO', 2, 1, '', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registroheaderlote', 'REGISTRO HEADER DE LOTE', 1, 8, '1', 1, true, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipooperacao', 'TIPO DA OPERACAO - INDICA DEBITO', 1, 9, 'C', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tiposervico', 'TIPO DO SERVICO', 2, 10, '30', 2, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'formalancamento', 'FORMA DE LANCAMENTO', 2, 12, '01', 2, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'layoutlote', 'LAYOUT DO LOTE', 1, 14, '040', 3, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 17, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipoinscricao', 'TIPO DE INSCRIÇÃO DA EMPRESA', 2, 18, '2', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'cgc', 'CGC DA PREFEITURA', 7, 19, '', 14, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'conveniobanco', 'CODIGO DO CONVENIO DO BANCO', 1, 33, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagenciacontalote', 'DIGITO VERIFICADOR DA AG/CONTA', 1, 72, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'nomeinst', 'NOME DA PREFEITURA', 1, 73, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'numero', 'NUMERO', 1, 173, '', 5, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db21_compl', 'COMPLEMENTO DO ENDEREÇO', 1, 178, '', 15, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'agencialote', 'AGENCIA MANTENEDORA DA CONTA', 2, 53, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagencialote', 'DIGITO VERIFICADOR DA AGENCIA', 1, 58, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'munic', 'NOME DA CIDADE', 1, 193, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'cep', 'CEP', 1, 213, '', 8, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'contalote', 'NUMERO DA CONTA CORRENTE', 2, 59, '', 12, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvcontalote', 'DIGITO VERIFICADOR DA CONTA', 1, 71, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'mensagemdoc', 'MENSAGEM DA PREFA EM AVISOS/DOCUMENTOS', 1, 103, 'PAGAMENTO DE SALARIO', 40, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'UsoexclusivoFEBRABAN/CNAB', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 223, '', 8, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'Codigosocorrencias', 'CÓDIGOS DAS OCORRÊNCIAS P/ RETORNO', 1, 231, '', 10, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'ender', 'LOGRADOURO', 1, 143, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'uf', 'SIGLA ESTADO', 1, 221, '', 2, false, true, 'd', '', 0);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'TRAILLER DE ARQUIVO', 5, 240, 0, 0, '', '', false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CODIGO DO BANCO NA COMPENSACAO', 2, 1, '237', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '9999', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registrotraillerarq', 'REGISTRO TRAILLER DE ARQUIVO', 1, 8, '9', 1, true, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 9, '', 9, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'quantidadelotesarq', 'QUANTIDADE DE LOTES DO ARQUIVO', 2, 18, '', 6, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'quantidaderegistarq', 'QUANTIDADE DE REGISTROS DO ARQUIVO', 2, 24, '', 6, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'quantidadecontasconc', 'QUANTIDADE DE CONTAS PARA CONCILIO', 2, 30, '', 6, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban2', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 36, '', 205, false, true, 'd', '', 0);

INSERT INTO configuracoes.db_layoutlinha (db51_codigo, db51_layouttxt, db51_descr, db51_tipolinha, db51_tamlinha, db51_linhasantes, db51_linhasdepois, db51_obs, db51_separador, db51_compacta) VALUES ((SELECT max(db51_codigo)+1 FROM db_layoutlinha), (SELECT max(db50_codigo) FROM db_layouttxt), 'HEADER DE ARQUIVO', 1, 240, 0, 0, '', '', false);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_codban', 'CÓDIGO DO BANCO NA COMPENSACAO', 2, 1, '237', 3, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'registroheaderarq', 'REGISTRO HEADER DE ARQUIVO', 2, 8, '0', 1, true, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban1', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 9, '', 9, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'tipoinscricao', 'TIPO DE INSCRIÇÃO DA EMPRESA', 2, 18, '2', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'cgc', 'CGC DA PREFEITURA', 7, 19, '', 14, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'loteservico', 'LOTE DE SERVICO', 2, 4, '0000', 4, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'brancos', 'BRANCOS', 1, 180, '', 69, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'conveniobanco', 'CODIGO DO CONVENIO DO BANCO', 1, 33, '', 20, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'reservadobanco', 'RESERVADO BANCO', 1, 172, '', 0, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'agenciaheader', 'AGENCIA MANTENEDORA DA CONTA', 2, 53, '', 5, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagenciaheader', 'DIGITO VERIFICADOR DA AGENCIA', 1, 58, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'contaheader', 'NUMERO DA CONTA CORRENTE', 2, 59, '', 12, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvcontaheader', 'DIGITO VERIFICADOR DA CONTA', 1, 71, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'dvagenciacontaheader', 'DIGITO VERIFICADOR DA AG/CONTA', 1, 72, '', 1, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'nomeinst', 'NOME DA PREFEITURA', 1, 73, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'db90_descr', 'NOME DO BANCO', 1, 103, '', 30, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'usofebraban2', 'USO EXCLUSIVO FEBRABAN/CNAB', 1, 133, '', 10, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'codigoremessa', 'INDICA QUE ARQUIVO E REMESSA', 2, 143, '1', 1, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'datageracao', 'DATA DE GERACAO DO ARQUIVO', 4, 144, '', 0, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'horageracao', 'HORA DE GERACAO DO ARQUIVO', 5, 152, '', 0, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'sequencialarq', 'NUMERO SEQUENCIAL DO ARQUIVO', 2, 158, '', 6, false, true, 'e', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'layoutarq', 'VERSAO DO LAYOUT DO ARQUIVO', 1, 164, '080', 3, false, true, 'd', '', 0);
INSERT INTO configuracoes.db_layoutcampos (db52_codigo, db52_layoutlinha, db52_nome, db52_descr, db52_layoutformat, db52_posicao, db52_default, db52_tamanho, db52_ident, db52_imprimir, db52_alinha, db52_obs, db52_quebraapos) VALUES ((SELECT max(db52_codigo)+1 FROM db_layoutcampos), (SELECT max(db51_codigo) FROM db_layoutlinha), 'densidadearquivo', 'DENSIDADE DE GRAVACAO DO ARQUIVO', 2, 167, '01600', 5, false, true, 'e', '', 0);
COMMIT;
SQL;
        $this->execute($sql);
    }
}
