<?php

use ECidade\Suporte\Phinx\PostgresMigration;

class Oc18098 extends PostgresMigration
{
    public function up()
    {

        $sql = <<<SQL

        BEGIN;

        SELECT fc_startsession();


        ALTER TABLE pagordem ADD COLUMN e50_cattrabalhador int4;
                    ALTER TABLE pagordem ADD COLUMN e50_empresadesconto int4;
                    ALTER TABLE pagordem ADD COLUMN e50_contribuicaoprev char;
                    ALTER TABLE pagordem ADD COLUMN e50_valorremuneracao float8;
                    ALTER TABLE pagordem ADD COLUMN e50_valordesconto float8;
                    ALTER TABLE pagordem ADD COLUMN  e50_datacompetencia date;

        Create table IF NOT EXISTS contabilidade.categoriatrabalhador(
                    ct01_codcategoria int8 not null,
                    ct01_descricaocategoria varchar(500) not null
                );

        INSERT INTO CATEGORIATRABALHADOR (CT01_CODCATEGORIA,CT01_DESCRICAOCATEGORIA) VALUES
        ('101','EMPREGADO - GERAL  INCLUSIVE O EMPREGADO PÚBLICO DA ADMINISTRAÇÃO DIRETA OU INDIRETA CONTRATADO PELA CLT'),
        ('102','EMPREGADO - TRABALHADOR RURAL POR PEQUENO PRAZO DA LEI 11.718/2008'),
        ('103','EMPREGADO - APRENDIZ'),
        ('104','EMPREGADO - DOMÉSTICO'),
        ('105','EMPREGADO - CONTRATO A TERMO FIRMADO NOS TERMOS DA LEI 9.601/1998'),
        ('106','TRABALHADOR TEMPORÁRIO - CONTRATO NOS TERMOS DA LEI 6.019/1974'),
        ('107','EMPREGADO - CONTRATO DE TRABALHO VERDE E AMARELO - SEM ACORDO PARA ANTECIPAÇÃO MENSAL DA MULTA RESCISÓRIA DO FGTS'),
        ('108','EMPREGADO - CONTRATO DE TRABALHO VERDE E AMARELO - COM ACORDO PARA ANTECIPAÇÃO MENSAL DA MULTA RESCISÓRIA DO FGTS'),
        ('111','EMPREGADO - CONTRATO DE TRABALHO INTERMITENTE'),
        ('201','TRABALHADOR AVULSO PORTUÁRIO'),
        ('202','TRABALHADOR AVULSO NÃO PORTUÁRIO'),
        ('301','SERVIDOR PÚBLICO TITULAR DE CARGO EFETIVO  MAGISTRADO  MINISTRO DE TRIBUNAL DE CONTAS  CONSELHEIRO DE TRIBUNAL DE CONTAS E MEMBRO DO MINISTÉRIO PÚBLICO'),
        ('302','SERVIDOR PÚBLICO OCUPANTE DE CARGO EXCLUSIVO EM COMISSÃO'),
        ('303','EXERCENTE DE MANDATO ELETIVO'),
        ('304','SERVIDOR PÚBLICO EXERCENTE DE MANDATO ELETIVO  INCLUSIVE COM EXERCÍCIO DE CARGO EM COMISSÃO'),
        ('305','SERVIDOR PÚBLICO INDICADO PARA CONSELHO OU ÓRGÃO DELIBERATIVO  NA CONDIÇÃO DE REPRESENTANTE DO GOVERNO  ÓRGÃO OU ENTIDADE DA ADMINISTRAÇÃO PÚBLICA'),
        ('306','SERVIDOR PÚBLICO CONTRATADO POR TEMPO DETERMINADO  SUJEITO A REGIME ADMINISTRATIVO ESPECIAL DEFINIDO EM LEI PRÓPRIA'),
        ('307','MILITAR'),
        ('308','CONSCRITO'),
        ('309','AGENTE PÚBLICO - OUTROS'),
        ('310','SERVIDOR PÚBLICO EVENTUAL'),
        ('311','MINISTROS  JUÍZES  PROCURADORES  PROMOTORES OU OFICIAIS DE JUSTIÇA À DISPOSIÇÃO DA JUSTIÇA ELEITORAL'),
        ('312','AUXILIAR LOCAL'),
        ('313','SERVIDOR PÚBLICO EXERCENTE DE ATIVIDADE DE INSTRUTORIA  CAPACITAÇÃO  TREINAMENTO  CURSO OU CONCURSO  OU CONVOCADO PARA PARECERES TÉCNICOS OU DEPOIMENTOS'),
        ('401','DIRIGENTE SINDICAL - INFORMAÇÃO PRESTADA PELO SINDICATO'),
        ('410','TRABALHADOR CEDIDO/EXERCÍCIO EM OUTRO ÓRGÃO/JUIZ AUXILIAR - INFORMAÇÃO PRESTADA PELO CESSIONÁRIO/DESTINO'),
        ('501','DIRIGENTE SINDICAL - SEGURADO ESPECIAL'),
        ('701','CONTRIBUINTE INDIVIDUAL - AUTÔNOMO EM GERAL  EXCETO SE ENQUADRADO EM UMA DAS DEMAIS CATEGORIAS DE CONTRIBUINTE INDIVIDUAL'),
        ('711','CONTRIBUINTE INDIVIDUAL - TRANSPORTADOR AUTÔNOMO DE PASSAGEIROS'),
        ('712','CONTRIBUINTE INDIVIDUAL - TRANSPORTADOR AUTÔNOMO DE CARGA'),
        ('721','CONTRIBUINTE INDIVIDUAL - DIRETOR NÃO EMPREGADO  COM FGTS'),
        ('722','CONTRIBUINTE INDIVIDUAL - DIRETOR NÃO EMPREGADO  SEM FGTS'),
        ('723','CONTRIBUINTE INDIVIDUAL - EMPRESÁRIO  SÓCIO E MEMBRO DE CONSELHO DE ADMINISTRAÇÃO OU FISCAL'),
        ('731','CONTRIBUINTE INDIVIDUAL - COOPERADO QUE PRESTA SERVIÇOS POR INTERMÉDIO DE COOPERATIVA DE TRABALHO'),
        ('734','CONTRIBUINTE INDIVIDUAL - TRANSPORTADOR COOPERADO QUE PRESTA SERVIÇOS POR INTERMÉDIO DE COOPERATIVA DE TRABALHO'),
        ('738','CONTRIBUINTE INDIVIDUAL - COOPERADO FILIADO A COOPERATIVA DE PRODUÇÃO'),
        ('741','CONTRIBUINTE INDIVIDUAL - MICROEMPREENDEDOR INDIVIDUAL'),
        ('751','CONTRIBUINTE INDIVIDUAL - MAGISTRADO CLASSISTA TEMPORÁRIO DA JUSTIÇA DO TRABALHO OU DA JUSTIÇA ELEITORAL QUE SEJA APOSENTADO DE QUALQUER REGIME PREVIDENCIÁRIO'),
        ('761','CONTRIBUINTE INDIVIDUAL - ASSOCIADO ELEITO PARA DIREÇÃO DE COOPERATIVA  ASSOCIAÇÃO OU ENTIDADE DE CLASSE DE QUALQUER NATUREZA OU FINALIDADE  BEM COMO O SÍNDICO OU ADMINISTRADOR ELEITO PARA EXERCER ATIVIDADE DE DIREÇÃO CONDOMINIAL  DESDE QUE RECEBAM REMUNERAÇÃO'),
        ('771','CONTRIBUINTE INDIVIDUAL - MEMBRO DE CONSELHO TUTELAR  NOS TERMOS DA LEI 8.069/1990'),
        ('781','MINISTRO DE CONFISSÃO RELIGIOSA OU MEMBRO DE VIDA CONSAGRADA  DE CONGREGAÇÃO OU DE ORDEM RELIGIOSA'),
        ('901','ESTAGIÁRIO'),
        ('902','MÉDICO RESIDENTE OU RESIDENTE EM ÁREA PROFISSIONAL DE SAÚDE'),
        ('903','BOLSISTA'),
        ('904','PARTICIPANTE DE CURSO DE FORMAÇÃO  COMO ETAPA DE CONCURSO PÚBLICO  SEM VÍNCULO DE EMPREGO/ESTATUTÁRIO'),
        ('906','BENEFICIÁRIO DO PROGRAMA NACIONAL DE PRESTAÇÃO DE SERVIÇO CIVIL VOLUNTÁRIO');


        COMMIT;

SQL;
        $this->execute($sql);
    }
}
