
networks:
  ecidade:
    driver: bridge

services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
          DB_SERVIDOR: bd
          DB_PORTA: '${DB_PORTA:-5432}'
        volumes:
            - './:/var/www/html'
        networks:
          - ecidade
        ports:
          - '${APP_PORT:-8282}:80'
        depends_on:
          bd:
            condition: service_healthy

    bd:
      image: ecidadecontass:bd
      restart: always
      ports:
        - "${DB_PORTA:-5432}:5432"
      build:
        context: ./docker/bd
        x-bake:
          no-cache: true
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        # POSTGRES_DB: ${DB_BASE}
        POSTGRES_INITDB_ARGS: '--encoding=LATIN1 --lc-collate=pt_BR.ISO-8859-1 --lc-ctype=pt_BR.ISO-8859-1 --lc-messages=pt_BR.ISO-8859-1 --lc-monetary=pt_BR.ISO-8859-1 --lc-numeric=pt_BR.ISO-8859-1 --lc-time=pt_BR.ISO-8859-1'
      volumes:
        - ./docker/scripts/iniciarbd.sql:/docker-entrypoint-initdb.d/iniciarbd.sql
        - './docker/bd/pgsql:/var/lib/postgresql/data'
      networks:
        - ecidade
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ecidade" ]
        interval: 10s
        timeout: 5s
        retries: 5

    adminer:
      image: adminer:latest
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: bd
        ADMINER_DEFAULT_USER: ecidade
        ADMINER_DEFAULT_PASSWORD: ecidade
        ADMINER_DEFAULT_TYPE: postgresql
        ADMINER_DEFAULT_PORT: "${DB_PORTA:-5432}:5432"
        ADMINER_DEFAULT_DB: ecidade
      networks:
        - ecidade
      ports:
        - "${ADMINER_PORT:-8484}:8080"
      depends_on:
        bd:
          condition: service_healthy

