SELECT fc_startsession();
begin;
insert into pctipocompratribunal values (48,'1','Convite','MG');
insert into pctipocompratribunal values (49,'2','Tomada de Precos','MG');
insert into pctipocompratribunal values (50,'3','Concorrencia','MG');
insert into pctipocompratribunal values (51,'4','Concurso','MG');
insert into pctipocompratribunal values (52,'5','Pregao presencial','MG');
insert into pctipocompratribunal values (53,'6','Pregao eletronico','MG');
insert into pctipocompratribunal values (54,'6','Leilao','MG');
insert into pctipocompratribunal values (100,'2','Inexigibilidade','MG');
insert into pctipocompratribunal values (101,'1','Dispensa de Licitacao','MG');
insert into pctipocompratribunal values (102,'3','Inexigibilidade Por Credenciamento','MG');
commit;
