select fc_startsession();
begin;
update acordocategoria set ac50_descricao = 'Contratos de gestão' where ac50_sequencial = 3;
update acordogarantia set ac11_descricao = 'CAUÇÃO EM DINHEIRO', ac11_obs = 'CAUÇÃO EM DINHEIRO',ac11_textopadrao = 'CAUÇÃO EM DINHEIRO' where ac11_sequencial = 1;
update acordogarantia set ac11_descricao = 'TÍTULO DA DÍVIDA PÚBLICA', ac11_obs = 'TÍTULO DA DÍVIDA PÚBLICA',ac11_textopadrao = 'TÍTULO DA DÍVIDA PÚBLICA' where ac11_sequencial = 2;
update acordogarantia set ac11_descricao = 'FIANÇA BANCÁRIA', ac11_obs = 'FIANÇA BANCÁRIA',ac11_textopadrao = 'FIANÇA BANCÁRIA' where ac11_sequencial = 4;
update acordopenalidade set ac13_descricao = 'MULTA RESCISÓRIA',ac13_obs = 'Descrição da previsão de multa rescisória, conforme previsão do art. 55, VII, da Lei Federal n. 8.666/93',ac13_textopadrao = 'Descrição da previsão de multa rescisória, conforme previsão do art. 55, VII, da Lei Federal n. 8.666/93' where ac13_sequencial = 1;
update acordopenalidade set ac13_descricao = 'MULTA INADIMPLEMENTO',ac13_obs= 'Descrição da previsão de multa por inadimplemento, conforme previsão do art. 55, VII, da Lei Federal n. 8.666/93',ac13_textopadrao = 'Descrição da previsão de multa por inadimplemento, conforme previsão do art. 55, VII, da Lei Federal n. 8.666/93' where ac13_sequencial = 2;
update db_itensmenu set descricao = 'Vigencia/Execucao', help = 'Aditamentos de Prazo de Vigência e/ou Execução' where id_item = 8588;
update db_itensmenu set descricao = 'Execução', help = 'Aditamentos de Prazo de Execução',libcliente = false where funcao = 'ac04_aditaexecucao.php';
update db_syscampo set descricao = 'Código sequencial da tabela',rotulo = 'Código Sequencial',rotulorel = 'Código Sequencial' where nomecam = 'ac54_sequencial';
update db_syscampo set descricao = 'Descrição da Lei',rotulo = 'Descrição',rotulorel = 'Descrição' where nomecam = 'ac54_descricao';
update db_itensmenu set descricao = 'Inclusão' where funcao = 'aco1_acordoleis001.php';
update db_itensmenu set descricao = 'Alteração' where funcao = 'aco1_acordoleis002.php';
update db_itensmenu set descricao = 'Exclusão' where funcao = 'aco1_acordoleis003.php';
update db_itensmenu set descricao = 'Inclusão' where funcao = 'sic1_apostilamentonovo001.php';
update db_itensmenu set descricao = 'Alteração' where funcao = 'sic1_apostilamentonovo002.php';
update db_itensmenu set descricao = 'Exclusão' where funcao = 'sic1_apostilamentonovo003.php';
commit;