<?
$campos = "licobrasresponsaveis.obr05_sequencial,licobrasresponsaveis.obr05_seqobra,licobrasresponsaveis.obr05_responsavel,licobrasresponsaveis.obr05_tiporesponsavel,licobrasresponsaveis.obr05_tiporegistro,licobrasresponsaveis.obr05_numregistro,licobrasresponsaveis.obr05_numartourrt,licobrasresponsaveis.obr05_vinculoprofissional,licobrasresponsaveis.obr05_instit";
?>
