<?
$campos = "eso05_sequencial,eso05_codclassificacaotributaria,eso05_indicativocooperativa,eso05_indicativodeconstrutora, eso05_indicativodesoneracao, eso05_microempresa,eso05_registroeletronicodeempregados,eso05_cnpjdoentefederativoresp,eso05_instit";
?>
