<?
$campos = "entesconsorciadosreceitas.c216_sequencial,entesconsorciadosreceitas.c216_enteconsorciado,entesconsorciadosreceitas.c216_tiporeceita,entesconsorciadosreceitas.c216_receita,entesconsorciadosreceitas.c216_saldo3112";
?>
