/**
 * Arquivo pre que desfaz as alterações do pre (up)
 */
delete from db_sysarqcamp where codarq in (3704, 3703);
delete from db_sysprikey  where codarq in (3704, 3703);
delete from db_sysforkey  where codarq in (3704, 3703);
delete from db_syscadind  where codind in (4063, 4064, 4065);
delete from db_sysindices where codind in (4063, 4064, 4065);
delete from db_syssequencia where codsequencia in (1000366, 1000365);

delete from db_syscampo   where codcam in (20581, 20582, 20583, 20584, 20586, 20587, 20588);
delete from db_sysarqmod  where codmod = 1008004 and codarq in (3704, 3703);
delete from db_sysarquivo where codarq in (3704, 3703);

drop table if exists funcaoatividade;
delete from db_sysprikey where codarq = 3706;
delete from db_sysarqcamp where codarq = 3706;
delete from db_syscampo where codcam in(20594, 20595, 20596);
delete from db_sysarqmod where codmod = 1008004 and codarq = 3706;
delete from db_sysarquivo where codarq = 3706;

delete from db_syscadind where codind = 4068;
delete from db_sysindices where codind = 4068;
delete from db_sysforkey where codarq = 1010095;
delete from db_sysarqcamp where codarq = 1010095;
delete from db_syscampo where codcam = 20597;

delete from db_menu      where id_item_filho in (9951, 9949, 9948);
delete from db_itensmenu where id_item in (9951, 9949, 9948);

/**
 * Estrutura turmaachorarioprofissional
 */
delete from db_syssequencia where codsequencia = 1000369;
delete from db_syscadind    where codind in ( 4071, 4072, 4073 );
delete from db_sysindices   where codind in ( 4071, 4072, 4073 );
delete from db_sysforkey    where codarq = 3709;
delete from db_sysprikey    where codarq = 3709;
delete from db_sysarqcamp   where codarq = 3709;
delete from db_sysarqmod    where codmod = 1008004 and codarq = 3709;
delete from db_sysarquivo   where codarq = 3709;
delete from db_syscampo     where codcam in( 20603, 20604, 20605, 20606, 20607, 20608, 20609 );

delete from avaliacaoperguntaopcaolayoutcampo where ed313_db_layoutcampo in(select db52_codigo from db_layoutcampos
                                                                             where db52_layoutlinha in (713, 714, 715, 716, 717, 718, 719, 720, 721, 722));

delete from db_layoutcampos  where db52_layoutlinha in (713, 714, 715, 716, 717, 718, 719, 720, 721, 722);
delete from db_layoutlinha where db51_layouttxt = 219;
delete from db_layouttxt where db50_codigo = 219;

--Municipios

delete from  escola.censomunic where ed261_i_codigo = 1504752;
update escola.censomunic set ed261_c_nome = 'SANTA ISABEL DO PARA' where ed261_i_codigo = 1506500;
update escola.censomunic set ed261_c_nome = 'PRESIDENTE JUSCELINO' where ed261_i_codigo = 2410306;
update escola.censomunic set ed261_c_nome = 'SERIDO' where ed261_i_codigo = 2515401;
update escola.censomunic set ed261_c_nome = 'IGUARACI' where ed261_i_codigo = 2606903;
update escola.censomunic set ed261_c_nome = 'BRASOPOLIS' where ed261_i_codigo = 3108909;
update escola.censomunic set ed261_c_nome = 'EMBU' where ed261_i_codigo = 3515004;
delete from  escola.censomunic where ed261_i_codigo = 4212650;
delete from  escola.censomunic where ed261_i_codigo = 4220000;
delete from  escola.censomunic where ed261_i_codigo = 4314548;
delete from  escola.censomunic where ed261_i_codigo = 5006275;

delete from db_syssequencia where codsequencia = 1000370;
delete from db_syscadind    where codind in ( 4074, 4075, 4076 );
delete from db_sysindices   where codind in ( 4074, 4075, 4076 );
delete from db_sysforkey    where codarq = 3710;
delete from db_sysprikey    where codarq = 3710;
delete from db_sysarqcamp   where codarq = 3710;
delete from db_syscampo     where codcam in ( 20610, 20611, 20612, 20613 );
delete from db_sysarqmod    where codmod = 1008004 and codarq = 3710;
delete from db_sysarquivo   where codarq = 3710;

--paises
update escola.pais set ed228_c_descr = 'BRUNEI' where ed228_i_codigo = 245;
update escola.pais set ed228_c_descr = 'MALI' where ed228_i_codigo = 206;
update escola.pais set ed228_c_descr = 'SINT MAARTEN (PARTE HOLANDESA)' where ed228_i_codigo = 5009;
update escola.pais set ed228_c_descr = 'REINO UNIDO DA GRA BRETANHA E IRLANDA DO NORTE' where ed228_i_codigo = 32;
delete from  escola.pais where ed228_i_paisonu = 834;
delete from db_syssequencia where codsequencia = 1000370;
delete from db_syscadind    where codind in ( 4074, 4075, 4076 );
delete from db_sysindices   where codind in ( 4074, 4075, 4076 );
delete from db_sysforkey    where codarq = 3710;
delete from db_sysprikey    where codarq = 3710;
delete from db_sysarqcamp   where codarq = 3710;
delete from db_syscampo     where codcam in ( 20610, 20611, 20612, 20613 );
delete from db_sysarqmod    where codmod = 1008004 and codarq = 3710;
delete from db_sysarquivo   where codarq = 3710;


--Atividade Complementar
delete from  escola.censoativcompl where ed133_i_codigo = 11006;
delete from  escola.censoativcompl where ed133_i_codigo = 11007;
delete from  escola.censoativcompl where ed133_i_codigo = 11008;
delete from  escola.censoativcompl where ed133_i_codigo = 11009;
delete from  escola.censoativcompl where ed133_i_codigo = 11010;
delete from  escola.censoativcompl where ed133_i_codigo = 12003;
delete from  escola.censoativcompl where ed133_i_codigo = 12004;
delete from  escola.censoativcompl where ed133_i_codigo = 12005;
delete from  escola.censoativcompl where ed133_i_codigo = 12006;
delete from  escola.censoativcompl where ed133_i_codigo = 12007;
update escola.censoativcompl set ed133_c_descr = 'OFICINA DE CINEMA, PROJECAO DE FILMES, CINECLUBE, ETC' where ed133_i_codigo = 13001;
update escola.censoativcompl set ed133_c_descr = 'LEITURA E TEATRO' where ed133_i_codigo = 14001;
delete from  escola.censoativcompl where ed133_i_codigo = 14004;
delete from  escola.censoativcompl where ed133_i_codigo = 15002;
delete from  escola.censoativcompl where ed133_i_codigo = 15003;
delete from  escola.censoativcompl where ed133_i_codigo = 15004;
delete from  escola.censoativcompl where ed133_i_codigo = 15005;
delete from  escola.censoativcompl where ed133_i_codigo = 17001;
delete from  escola.censoativcompl where ed133_i_codigo = 17002;
update escola.censoativcompl set ed133_c_descr = 'OUTRA CATEGORIA DE ARTE E CULTURA' where ed133_i_codigo = 19999;
update escola.censoativcompl set ed133_c_descr = 'BRINCADEIRAS, JOGOS NAO ESTRUTURADOS, RECREACAO/LAZER FESTAS ETC.' where ed133_i_codigo = 21001;
update escola.censoativcompl set ed133_c_descr = 'YOGA' where ed133_i_codigo = 22007;
update escola.censoativcompl set ed133_c_descr = 'ETNOJOGOS (SOMENTE PARA ESCOLAS DO CAMPO)' where ed133_i_codigo = 22010;
delete from  escola.censoativcompl where ed133_i_codigo = 22011;
delete from  escola.censoativcompl where ed133_i_codigo = 22012;
delete from  escola.censoativcompl where ed133_i_codigo = 22013;
delete from  escola.censoativcompl where ed133_i_codigo = 22014;
delete from  escola.censoativcompl where ed133_i_codigo = 22015;
delete from  escola.censoativcompl where ed133_i_codigo = 22016;
delete from  escola.censoativcompl where ed133_i_codigo = 22017;
delete from  escola.censoativcompl where ed133_i_codigo = 22018;
delete from  escola.censoativcompl where ed133_i_codigo = 22019;
delete from  escola.censoativcompl where ed133_i_codigo = 22020;
delete from  escola.censoativcompl where ed133_i_codigo = 22021;
delete from  escola.censoativcompl where ed133_i_codigo = 22022;
delete from  escola.censoativcompl where ed133_i_codigo = 22023;
delete from  escola.censoativcompl where ed133_i_codigo = 22024;
delete from  escola.censoativcompl where ed133_i_codigo = 22025;
delete from  escola.censoativcompl where ed133_i_codigo = 22026;
delete from  escola.censoativcompl where ed133_i_codigo = 22027;
delete from  escola.censoativcompl where ed133_i_codigo = 22028;
delete from  escola.censoativcompl where ed133_i_codigo = 22029;
delete from  escola.censoativcompl where ed133_i_codigo = 22030;
delete from  escola.censoativcompl where ed133_i_codigo = 22031;
update escola.censoativcompl set ed133_c_descr = 'PORTUGUES' where ed133_i_codigo = 31002;
update escola.censoativcompl set ed133_c_descr = 'CIENCIAS: CINETICA QUIMICA, REACOES QUIMICAS, ELETROQUIMICA, QUIMICA ORGANICA, FISICA OTICA, CIRCUITOS ELETRICOS, CALOMETRIA, CELULA ANIMAL, ESTRUTURA DO DNA E COLETA DE SANGUE' where ed133_i_codigo = 31004;
update escola.censoativcompl set ed133_c_descr = 'LINGUAS ESTRANGEIRAS E INDIGENAS' where ed133_i_codigo = 31006;
update escola.censoativcompl set ed133_c_descr = 'LEITURA E PRODUCAO DE TEXTO' where ed133_i_codigo = 31007;
update escola.censoativcompl set ed133_c_descr = 'ETNOLINGUAGEM (SOMENTE PARA ESCOLAS DO CAMPO)' where ed133_i_codigo = 31011;
delete from  escola.censoativcompl where ed133_i_codigo = 31012;
delete from  escola.censoativcompl where ed133_i_codigo = 31013;
delete from  escola.censoativcompl where ed133_i_codigo = 31014;
delete from  escola.censoativcompl where ed133_i_codigo = 41007;
delete from  escola.censoativcompl where ed133_i_codigo = 41008;
delete from  escola.censoativcompl where ed133_i_codigo = 41009;
delete from  escola.censoativcompl where ed133_i_codigo = 41010;
delete from  escola.censoativcompl where ed133_i_codigo = 41011;
delete from  escola.censoativcompl where ed133_i_codigo = 41012;
delete from  escola.censoativcompl where ed133_i_codigo = 71007;
update escola.censoativcompl set ed133_c_descr = 'OUTRA CATEGORIA DE PREVENCAO E PROMOCAO DA SAUDE' where ed133_i_codigo = 79999;
update escola.censoativcompl set ed133_c_descr = 'PETI - MINISTERIO DO DESENVOLVIMENTO SOCIAL E COMBATE A FOME/MDS' where ed133_i_codigo = 91001;
update escola.censoativcompl set ed133_c_descr = 'PROGRAMA SEGUNDO TEMPO (MINISTERIO DOS ESPORTES)' where ed133_i_codigo = 91002;
delete from  escola.censoativcompl where ed133_i_codigo = 10103;
update escola.censoativcompl set ed133_c_descr = 'OUTRA CATEGORIA DE INVESTIGACAO NO CAMPO DAS CIENCIAS DA NATUREZA (EDUCACAO CIENTIFICA)' where ed133_i_codigo = 10999;
delete from  escola.censoativcompl where ed133_i_codigo = 13101;
delete from  escola.censoativcompl where ed133_i_codigo = 13102;
delete from  escola.censoativcompl where ed133_i_codigo = 13103;
delete from  escola.censoativcompl where ed133_i_codigo = 13104;
delete from  escola.censoativcompl where ed133_i_codigo = 13105;
delete from  escola.censoativcompl where ed133_i_codigo = 13201;
delete from  escola.censoativcompl where ed133_i_codigo = 13999;
delete from  escola.censoativcompl where ed133_i_codigo = 14101;
delete from  escola.censoativcompl where ed133_i_codigo = 14102;
delete from  escola.censoativcompl where ed133_i_codigo = 14103;
delete from  escola.censoativcompl where ed133_i_codigo = 14104;
delete from  escola.censoativcompl where ed133_i_codigo = 14105;
delete from  escola.censoativcompl where ed133_i_codigo = 14201;
delete from  escola.censoativcompl where ed133_i_codigo = 14202;
delete from  escola.censoativcompl where ed133_i_codigo = 14203;
delete from  escola.censoativcompl where ed133_i_codigo = 14999;

--ensino superior
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE ESTADUAL DE CIENCIAS DA SAUDE DE ALAGOAS - UNCISAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 32;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DE ARARAS -',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 125;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE DIREITO DE VARGINHA - FADIVA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 141;
update escola.censoinstsuperior   set ed257_c_nome = 'CONSERVATORIO BRASILEIRO DE MUSICA - CENTRO UNIVERSITARIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 158;
update escola.censoinstsuperior   set ed257_c_nome = 'FAI - CENTRO DE ENSINO SUPERIOR EM GESTAO, TECNOLOGIA E EDUCACAO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 166;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA DE MEDICINA SOUZA MARQUES DA FUNDACAO TECNICO-EDUCACIONAL SOUZA MARQUES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 190;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE MORAES JUNIOR - MACKENZIE RIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 195;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO ITALO-BRASILEIRO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 206;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ENGENHARIA DE MINAS GERAIS - FEAMIG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 214;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DAS FACULDADES ASSOCIADAS DE ENSINO - FAE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 217;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE SAO BERNARDO DO CAMPO - FASB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 231;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ENGENHARIA E AGRIMENSURA DE PIRASSUNUNGA - FEAP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 255;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE CIENCIAS APLICADAS - ISCA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 346;
update escola.censoinstsuperior   set ed257_c_nome = 'FOCCA - FACULDADE DE OLINDA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 405;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO LUTERANO DE JI-PARANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 450;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE BANDEIRANTE DE SAO PAULO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 457;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE COMUNICACAO E MARKETING DA - FUNDACAO ARMANDO ALVARES PENTEADO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 463;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS SOCIAIS APLICADAS DO SUL DE MINAS - FACESM',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 508;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO PLINIO LEITE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 515;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE MANDAGUARI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 535;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE FEDERAL RURAL DO SEMI-ARIDO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 589;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE FEDERAL DE ITAJUBA - UNIFEI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 598;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS PROFESSORA NAIR FORTES ABU-MERHY',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 615;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES ASSOCIADAS DE UBERABA - FAZU',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 648;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE ANHANGUERA - UNIDERP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 671;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS ANGLO-AMERICANO',       ed257_c_situacao = 'INATIVA' where ed257_i_codigo = 681;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO FRANCISCANO DO PARANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 715;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO SAO CAMILO - ESPIRITO SANTO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 739;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA THEREZA PORTO MARQUES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 778;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO ESTACIO RADIAL DE SAO PAULO - ESTACIO UNIRADIAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 793;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE DIREITO E CIENCIAS SOCIAIS DO LESTE DE MINAS - FADILESTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 809;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO TECNICO-EDUCACIONAL SUPERIOR DO OESTE PARANAENSE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 810;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE DO CEUMA - UNICEUMA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 823;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DE DESENVOLVIMENTO DO CENTRO-OESTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 826;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS DE PARANAIBA - FIPAR',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 913;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS AGRO- AMBIENTAIS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 954;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TURISMO - SANTOS DUMONT',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 966;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SENAI-CETIQT',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 991;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE FLAMA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 994;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR E CENTRO EDUCACIONAL LUTERANO - BOM JESUS - IELUSC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1014;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS E TECNOLOGIA DE UNAI - FACTU',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1019;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS CONTABEIS - MACEIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1051;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO ESTACIO DA BAHIA - ESTACIO FIB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1058;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DO INSTITUTO DE EDUCACAO SUPERIOR DE BRASILIA - IESB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1060;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO DO RECIFE - ESTACIO FIR',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1077;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE PRESIDENTE EPITACIO - FAPE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1096;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS GERENCIAIS - COTIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1108;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO EURO-AMERICANO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1113;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ESTUDOS ADMINISTRATIVOS DE MINAS GERAIS - FEAD-MG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1139;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA  DA PARAIBA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1166;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DE MARINGA - CEUMAR',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1196;
update escola.censoinstsuperior   set ed257_c_nome = 'FAL ESTACIO - FACULDADE ESTACIO DE NATAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1208;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO LATINO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1215;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SAO FRANCISCO DE BARREIRAS - FASB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1227;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS CONTABEIS DE NOVA ANDRADINA - FACINAN',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1247;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DO INSTITUTO DE ENSINO SUPERIOR COC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1270;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ITAPOLIS - FACITA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1279;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO COTIA - ESTACIO FAAC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1280;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ALBERT EINSTEIN DE SAO PAULO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1290;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO DE ALAGOAS - ESTACIO FAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1298;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS SOCIAIS APLICADAS - FACISA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1334;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR TUPY - IST',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1351;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR DE TEOLOGIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1382;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DINAMICA DAS CATARATAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1396;
update escola.censoinstsuperior   set ed257_c_nome = 'AREA1 - FACULDADE DE CIENCIA E TECNOLOGIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1410;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO PLANALTO DO DISTRITO FEDERAL - UNIPLAN',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1446;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO DO CERRADO-PATROCINIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1450;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO EURO- PANAMERICANA DE HUMANIDADES E TECNOLOGIAS - ESTACIO EUROPAN',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1457;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANCHIETA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1478;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE CENECISTA DE JOINVILLE - FACE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1530;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA SUL-RIO-GRANDENSE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1578;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS HUMANAS E SOCIAIS APLICADAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1590;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ADMINISTRACAO DE NOVA ANDRADINA - FANOVA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1605;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR DE CRICIUMA - ESUCRI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1694;
update escola.censoinstsuperior   set ed257_c_nome = 'ESTACIO ATUAL - FACULDADE ESTACIO DA AMAZONIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1702;
update escola.censoinstsuperior   set ed257_c_nome = 'IMP DE ENSINO SUPERIOR - IMP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1739;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA ALBERT EINSTEIN',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1745;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE LUSO-BRASILEIRA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1749;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE MAUA - FAMA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1804;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA  DO AMAZONAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1812;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SUL-AMERICANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1822;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1828;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO FUNDACAO DE ENSINO OCTAVIO BASTOS - FEOB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1836;
update escola.censoinstsuperior   set ed257_c_nome = 'FEFISA - FACULDADES INTEGRADAS DE SANTO ANDRE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1845;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA DE NEGOCIOS DO ESTADO DA BAHIA - ENEB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1893;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA DE ENSINO SUPERIOR ALTERNATIVO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1908;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS EXATAS E TECNOLOGICAS SANTO AGOSTINHO - FACET',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1919;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO DE ENSINO SUPERIOR DE LONDRINA - INESUL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1939;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DOS IMIGRANTES - FAI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 1969;
update escola.censoinstsuperior   set ed257_c_nome = 'SEMINARIO ADVENTISTA LATINO-AMERICANO DE TEOLOGIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2001;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JK - UNIDADE II - GAMA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2021;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIAO LATINO-AMERICADA DE TECNOLOGIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2035;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO DO PARA - ESTACIO FAP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2036;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE FIGUEIREDO COSTA - FIC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2042;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2077;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE EDUCACAO PRO-SABER',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2091;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO DE SERGIPE - ESTACIO FASE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2122;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SANT''ANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2160;
update escola.censoinstsuperior   set ed257_c_nome = 'RATIO - FACULDADE TEOLOGICA E FILOSOFICA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2180;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE FREGUESIA DO O',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2197;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE UNIAO AMERICANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2246;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE STELLA MARIS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2256;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS DE ANGELES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2289;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE CANDIDO RONDON - FCR',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2330;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ESTACIO DO AMAPA - ESTACIO FAMAP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2380;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE INTEGRADA BRASIL AMAZONIA - FIBRA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2426;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE DIREITO PROMOVE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2450;
update escola.censoinstsuperior   set ed257_c_nome = 'FACUDADE IEDUCARE - FIED',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2466;
update escola.censoinstsuperior   set ed257_c_nome = 'FIAM-FAAM - CENTRO UNIVERSITARIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2556;
update escola.censoinstsuperior   set ed257_c_nome = 'ABEU - CENTRO UNIVERSITARIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2565;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA IBTA - SAO JOSE DOS CAMPOS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2625;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO SUPERIOR DO PIEMONTE DA CHAPADA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2653;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE INESP - INSTITUTO NACIONAL DE ENSINO E PESQUISA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2688;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DO CENTRO-OESTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2695;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS EDUCACIONAIS CAPIM GROSSO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2753;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS DESEMBARGADOR SAVIO BRANDAO - FAUSB',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2775;
update escola.censoinstsuperior   set ed257_c_nome = 'FANEESP - FACULDADE NACIONAL DE EDUCACAO E ENSINO SUPERIOR DO PARANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2799;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JK - GUARA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2904;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE MARIA MILZA - CAMPUS FACTAE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2912;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR DE ADMINISTRACAO, DIREITO E ECONOMIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 2950;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DO INSTITUTO NACIONAL DE POS-GRADUACAO DE CAMPINAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3007;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DO INSTITUTO NACIONAL DE POS-GRADUACAO DE SAO JOSE DOS CAMPOS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3008;
update escola.censoinstsuperior   set ed257_c_nome = 'FAJOPA - FACULDADE JOAO PAULO II',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3012;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE POTIGUAR DA PARAIBA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3099;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE PITAGORAS DE DIVINOPOLIS - FPD',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3149;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE EDUCACAO ANGLO-AMERICANO DE FOZ DO IGUACU',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3158;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA  DE SANTA CATARINA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3162;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA  DO TRIANGULO MINEIRO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3165;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS DA BAHIA - FACIBA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3216;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ALFA BRASIL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3242;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA ENIAC-FAPI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3294;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS MATO-GROSSENSES DE CIENCIAS SOCIAIS E HUMANAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3303;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO DE EDUCACAO SUPERIOR PRESIDENTE KENNEDY - CENTRO DE FORMACAO DE PROFISSIONAIS DE EDUCACAO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3360;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE MARKETING E NEGOCIOS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3430;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DA FRONTEIRA - FAF',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3502;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE VICENTINA - FAVI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3509;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TEOLOGIA EVANGELICA EM CURITIBA - FATEV',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3536;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS TORRICELLI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3603;
update escola.censoinstsuperior   set ed257_c_nome = 'SINAL - FACULDADE DE TEOLOGIA E FILOSOFIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3675;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE PORTAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3699;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO DE BACABAL - FEBAC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3741;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO DE EDUCACAO SUPERIOR UNICA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3758;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE OMNI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3760;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE IBGEN - INSTITUTO BRASILEIRO DE GESTAO DE NEGOCIOS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3768;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SENAC PORTO ALEGRE - FSPOA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3804;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO CENTRO DE ENSINO TECNOLOGICO - SOBRAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3830;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DAS AGUAS EMENDADAS - FAE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3854;
update escola.censoinstsuperior   set ed257_c_nome = 'AVM - FACULDADE INTEGRADA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3876;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JK - BRASILIA - UNIDADE PLANO PILOTO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3980;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JK - ASA NORTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3992;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA INFNET RIO DE JANEIRO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 3998;
update escola.censoinstsuperior   set ed257_c_nome = 'FATECE - FACULDADE DE TECNOLOGIA, CIENCIAS E EDUCACAO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4007;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE TECNOLOGIA EDUVALE - AVARE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4043;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE BATISTA DO ESTADO DO RIO DE JANEIRO - FABERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4066;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE EDUCACAO DO ICESP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4068;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA IBRATEC DE JOAO PESSOA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4094;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA TECBRASIL - UNIDADE PORTO ALEGRE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4096;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA TECBRASIL - UNIDADE BENTO GONCALVES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4097;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR DE ENGENHARIA E GESTAO DE SAO PAULO - ESEG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4104;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JOAQUIM NABUCO - PAULISTA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4118;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE SANTA DOROTEIA DO AMAZONAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4135;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO UNIFICADO EUROPEU DO BRASIL IUNE-BRASIL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4175;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA INED - UNIDADE IPATINGA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4204;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE DIREITO DE PEDRO LEOPOLDO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4218;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE EDUCACAO PROFESSORA NAIR FORTES ABU-MERHY',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4219;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE INHUMAS - FAC-MAIS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4259;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DO VALE ELVIRA DAYRELL - FAVED',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4289;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DO CENTRO EDUCACIONAL MINEIRO - FACEM',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4329;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE PANAMERICANA DE JI-PARANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4411;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE JK - UNIDADE I - GAMA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4416;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE ENFERMAGEM NOVA ESPERANCA DE MOSSORO - FACENE/RN',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4431;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR PAULISTA DE ADMINISTRACAO - ESPA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4442;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE CIDADE DE GUANHAES - FACIG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4446;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS CAMPO-GRANDENSES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4502;
update escola.censoinstsuperior   set ed257_c_nome = 'ESTACIO FATERN - FACULDADE ESTACIO DO RIO GRANDE DO NORTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4566;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE CENTRO MATO-GROSSENSE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4567;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA CONTEC - UNIDADE DE CARAPINA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4606;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO DE JOAO PESSOA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4631;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO DE CAXIAS DO SUL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4632;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO DE PASSO FUNDO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4633;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ALTERNATIVA DE ENSINO SUPERIOR DO AGRESTE - FAESA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4714;
update escola.censoinstsuperior   set ed257_c_nome = 'AMADO@ASSOCIADOS IRH S C LTDA',       ed257_c_situacao = 'INATIVA' where ed257_i_codigo = 4755;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE BI MINAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4773;
update escola.censoinstsuperior   set ed257_c_nome = 'FACISA-UNAI FACULDADE DE CIENCIAS DA SAUDE DE UNAI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4780;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO CENTRO DE ENSINO TECNOLOGICO - CARIRI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4788;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO CENTRO DE ENSINO TECNOLOGICO - LIMOEIRO DO NORTE',       ed257_c_situacao = 'INATIVA' where ed257_i_codigo = 4789;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA CENTEC - CARIRI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4791;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA SUPERIOR DE ENGENHARIA E GESTAO DE VALINHOS - ESEG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4794;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS GERENCIAIS E EMPREENDEDORISMO - FACIGE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4821;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO  ACREANO EUCLIDES DA CUNHA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4836;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA FAESA - UNIDADE GUARAPARI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4859;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA PITAGOTAS - UNIDADE LONDRINA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4869;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA CENTEC - SERTAO CENTRAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 4992;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DO IBRATE FAITEC *',       ed257_c_situacao = 'INATIVA' where ed257_i_codigo = 4993;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5016;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5017;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5020;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5021;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5051;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE EDUCACAO TECNOLOGICA DO ESTADO DO RIO DE JANEIRO - FAETERJ',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5052;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE TECNOLOGIA DE PARACAMBI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5053;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO SUPERIOR DE EDUCACAO ANTONINO FREIRE - ISEAF',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5204;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE UIRAPURU',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5216;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE ESTADUAL DE ALAGOAS - UNEAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5242;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE PORTO-ALEGRENSE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5317;
update escola.censoinstsuperior   set ed257_c_nome = 'FUNDACAO UNIVERSIDADE FEDERAL DO PAMPA - UNIPAMPA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5322;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO DE ENSINO SUPERIOR INTEGRADO-IESI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5394;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE MINAS GERAIS - FATEMIG',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5430;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS DA UNIAO EDUCACIONAL DO PLANALTO CENTRAL - FACIPLAC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5439;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES VALE DO CARANGOLA - FAVALE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5537;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES INTEGRADAS DO NORTE DE MINAS - FUNORTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5592;
update escola.censoinstsuperior   set ed257_c_nome = 'LIBERTAS - FACULDADES INTEGRADAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5599;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE CIENCIAS HUMANAS E SOCIAIS DE ARARIPINA - FACISA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 5664;
update escola.censoinstsuperior   set ed257_c_nome = 'FAMAC - FACULDADE DE MACHADINHO DO OESTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 10009;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE OBOE - FACO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 10016;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE ENSINO SUPERIOR - FATEC',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 10059;
delete from  escola.censoinstsuperior where ed257_i_codigo = 10349;
delete from  escola.censoinstsuperior where ed257_i_codigo = 11376;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DA SERRA GAUCHA - CAXIAS DO SUL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11563;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADES NETWORK - CAMPUS SUMARE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11586;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO DE CHAPECO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11604;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE PITAGORAS DE VOTORANTIM - SOROCABA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11750;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA INED - UNIDADE BETIM',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11751;
update escola.censoinstsuperior   set ed257_c_nome = 'INSTITUTO NACIONAL DE ENSINO SUPERIOR E POS-GRADUACAO PADRE GERVASIO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 11860;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA INED - UNIDADE VENDA NOVA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12005;
delete from  escola.censoinstsuperior where ed257_i_codigo = 12136;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA FAESA - VILA VELHA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12229;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA LA SALLE - ESTRELA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12338;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DA SERRA GAUCHA - BENTO CONCALVES',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12523;
update escola.censoinstsuperior   set ed257_c_nome = 'FACITEN - FACULDADE DE CIENCIAS E TECNOLOGIAS DE NATAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12547;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE TEOLOGICA DA ASSEMBLEIA DE DEUS EM CURITIBA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12754;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA SENAC MINAS - UNIDADE BELO HORIZONTE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12772;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA TECBRASIL - UNIDADE NOVO HAMBURGO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12784;
delete from  escola.censoinstsuperior where ed257_i_codigo = 12791;
delete from  escola.censoinstsuperior where ed257_i_codigo = 12829;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA SENAC MINAS - UNIDADE BARBACENA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12848;
update escola.censoinstsuperior   set ed257_c_nome = 'IPOG - INSTITUTO DE POS-GRADUACAO & GRADUACAO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 12916;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE GOIANIA - UNIDADE 1',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13133;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE ANGLO-AMERICANO DE BAGE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13359;
delete from  escola.censoinstsuperior where ed257_i_codigo = 13648;
delete from  escola.censoinstsuperior where ed257_i_codigo = 13783;
delete from  escola.censoinstsuperior where ed257_i_codigo = 13784;
delete from  escola.censoinstsuperior where ed257_i_codigo = 13792;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE LA SALLE - CAXIAS',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13818;
update escola.censoinstsuperior   set ed257_c_nome = 'ESCOLA DE CIENCIAS DO TRABALHO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13845;
update escola.censoinstsuperior   set ed257_c_nome = 'FATEC- FACULDADE SENAI DE TECNOLOGIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13878;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA BSG-U',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 13890;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE APROVACAO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 14403;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14412;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14785;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14786;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14878;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14879;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14927;
delete from  escola.censoinstsuperior where ed257_i_codigo = 14961;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE FEDERAL DA INTEGRACAO LATINO-AMERICANA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15001;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE MASTER DE PARAUAPEBAS - FAMAP',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15079;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15272;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15280;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15351;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15382;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15445;
update escola.censoinstsuperior   set ed257_c_nome = 'UNIVERSIDADE DA INTEGRACAO INTERNACIONAL DA LUSOFONIA AFRO-BRASILEIRA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15497;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15501;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15502;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15504;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15518;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15521;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE SAO JOSE DOS CAMPOS - JESSEN VIDAL',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15581;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE ITAPETININGA - PROF.ANTONIO BELIZANDRO BARBOSA REZENDE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15693;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE OSASCO - PREFEITO HIRANT SANAZAR',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15709;
update escola.censoinstsuperior   set ed257_c_nome = 'FATEC ARTHUR AZEVEDO - MOGI MIRIM',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15714;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15777;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA ESTUDANTE RAFAEL ALMEIDA CAMARINHA - MARILIA',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15784;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE DE TECNOLOGIA DE TATUI - PROF. WILSON ROBERTO RIBEIRO DE CAMARGO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 15803;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15859;
delete from  escola.censoinstsuperior where ed257_i_codigo = 15873;
delete from  escola.censoinstsuperior where ed257_i_codigo = 16037;
update escola.censoinstsuperior   set ed257_c_nome = 'FACULDADE REGIONAL DE TIMBO',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 16914;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO UNIVERSITARIO - CAT?A DE SANTA CATARINA EM JOINVILLE',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 17138;
update escola.censoinstsuperior   set ed257_c_nome = 'CENTRO DE EDUCACAO SUPERIOR DA FOZ DO ITAJAI - CESFI',       ed257_c_situacao = 'ATIVA' where ed257_i_codigo = 17633;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17691;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17775;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17942;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17952;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17953;
delete from  escola.censoinstsuperior where ed257_i_codigo = 17977;
delete from  escola.censoinstsuperior where ed257_i_codigo = 18049;
delete from  escola.censoinstsuperior where ed257_i_codigo = 18099;
delete from  escola.censoinstsuperior where ed257_i_codigo = 18440;
delete from  escola.censoinstsuperior where ed257_i_codigo = 18506;
delete from  escola.censoinstsuperior where ed257_i_codigo = 18812;


delete from avaliacaoperguntaopcaolayoutcampo where ed313_avaliacaoperguntaopcao in (3000571, 3000572,3000573,3000574, 3000575,3000576);
delete from avaliacaoperguntaopcao where db104_sequencial in(3000571, 3000572,3000573,3000574, 3000575, 3000576);
delete from avaliacaopergunta where db103_sequencial in(3000154, 3000155,3000156, 3000157, 3000158, 3000159);